### ISSUE TITLE
Can't pull jetbrains/teamcity-base

### ISSUE THREAD

**Issue by jeandet** [JetBrains/teamcity-docker-server#10]
I want to modify a bit the image to integrate pgsql driver and add mercurial(missing in last image), but pulling base image give me this:
``` bash
Using default tag: latest
Trying to pull repository docker.io/jetbrains/teamcity-base ... 
unauthorized: authentication required
```

**Comment by jeandet** [comment]
Ok, I just saw the closed issue #8. 
I made my own image [here](https://github.com/jeandet/teamcity-docker-server), it seems that a raw fedora with openJDK is enough, I didn't test that much but it seems to work.
The readme is really misleading, since we assume that we can build our own image from this repo.

**Comment by VladRassokhin** [comment]
Sorry for inconvenience, we are using `ubuntu:xenial` as a base with curl and unzip installed.
Then we adding latest Oracle JDK 8, but you may add OpenJDK 8.

**Comment by dtretyakov** [comment]
@jeandet, thanks for reporting it. Instruction was updated:
https://github.com/JetBrains/teamcity-docker-server/
