### ISSUE TITLE
Provide popular jdbc drivers

### ISSUE THREAD

**Issue by fred01** [JetBrains/teamcity-docker-server#11]
Hi!
It will be nice if you include mysql and podtgres jdbc driver into this image, isn't it?
Now my docker file looks like 
```
FROM jetbrains/teamcity-server:latest

WORKDIR /root

RUN apt-get update && apt-get install -y wget

RUN wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.40.tar.gz && \
    tar xvzf mysql-connector-java-5.1.40.tar.gz && \
    cp mysql-connector-java-5.1.40/mysql-connector-java-5.1.40-bin.jar /opt/teamcity/lib && \
    rm -rf mysql-connector-java-5.1.40*
```
So, i should rebuild my image every time you upgrade yours. I don't think that drivers dramatically increased size of your image, but dramatically improved convenience of it using.

**Comment by VladRassokhin** [comment]
Hi, 
Thank you for reporting.
We would think about adding such images or just special tags to existing one. Also there's [related issue in our tracker](https://youtrack.jetbrains.com/issue/TW-47920), so you may watch/vote for it there.

BTW, last RUN command in your script could be simplified to
```Dockerfile
RUN wget http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.42/mysql-connector-java-5.1.42.jar -O /opt/teamcity/lib/mysql-connector-java-5.1.42.jar
```

**Comment by fred01** [comment]
Hi!
Thank you for a quick answer, i'd vote for youtrack issue too. Hope it help to solve it faster :)

**Comment by pavelsher** [comment]
Please watch for progress in our tracker: https://youtrack.jetbrains.com/issue/TW-47920
