### ISSUE TITLE
Install git

### ISSUE THREAD

**Issue by aaronjensen** [JetBrains/teamcity-docker-server#12]
We get this error in teamcity:

```
Cannot run git garbage collection using git at path 'git': 'git version' command failed. exception: Cannot run program "git" (in directory "/data/teamcity_server/datadir/system/caches/git"): error=2, No such file or directory exit code: -1. 
Please install a git client on the TeamCity server machine and specify a path to it in the teamcity.server.git.executable.path internal property.
```

It'd be nice if this docker image had git built in. Thanks!

**Comment by pavelhritonenko** [comment]
Faced the same issue for `TeamCity Professional 2017.1.3 (build 46961)`

**Comment by spacentropy** [comment]
I get the same error with 2017.1.3.

**Comment by VladRassokhin** [comment]
Fixed, added both git and mercurial into server image, would be available in 2017.2

**Comment by pavelhritonenko** [comment]
@VladRassokhin Is it pushed to docker hub automatically?

**Comment by VladRassokhin** [comment]
It would be pushed to docker hub once TeamCity 2017.2 (release or at least eap) would be released, so nothing pushed yet.

**Comment by pavelhritonenko** [comment]
Any estimates when it will be done? Is not urgent though

**Comment by VladRassokhin** [comment]
TeamCity 2017.2 is planned for Q4 2017. Probably we would have several EAPs before that.

If you need git in 2017.1.x  you can create another Docker image on top of 'jetbrains/teamcity-server'

**Comment by timmclaurin** [comment]
@VladRassokhin any chance you could give a n00b pointers on " you can create another Docker image on top of 'jetbrains/teamcity-server'"?

**Comment by VladRassokhin** [comment]
@timmclaurin I can only recommend something like:
1. Create Dockerfile with content like 
```
FROM jetbrains/teamcity-server:latest
RUN some apt-get commands
```
2. run `docker build -t custom-teamcity-server`

**Comment by timmclaurin** [comment]
That easy.... Sigh!  thank you for humoring the n00b and sharing clear knowledge

**Comment by Lexus-3141** [comment]
Hi, I caught it on 2018.2.2 (build 61245) on Windows.  
I fix it installed Git manually and set teamcity internal property.
Actually /system/caches/git doesn't contains git binaries.

**Comment by titobf** [comment]
@Lexus-3141 Hi, I appreciate if you share here how did you set the internal property. 
Did you set it like: `teamcity.server.git.executable.path=C:\Program Files\Git\bin\git.exe` ?
Thanks

**Comment by NetRom2-CPI** [comment]
@titobf I fixed mine with:
teamcity.server.git.executable.path="C:\\Program Files\\Git\\bin\\git.exe"
