### ISSUE TITLE
Server fails to start up if database is not available

### ISSUE THREAD

**Issue by AndrewSav** [JetBrains/teamcity-docker-server#20]
I asked on a docker-related media:

>If I have an app container and a database container the app depends on, how do I make sure (in rancher) that app only starts when database is already up? I want to keep them in the same stack and I configured the database as a sidekick, but it is not working very well as rancher starts the sidekick after the main container starts.

The answer I got was:

>TL;DR: Don't, dependency ordering only pretends to solve problems; what would you do if the DB container dies or restarts? The container should know how to wait for and reconnect to its dependencies, or exit if they're unavailable and get restarted/rescheduled later.

If I cannot use dependency ordering to make sure that the database in a container is up and running, then it's up for teamcity server to keep re-trying while it waits for the database come up.

It does not seem to be doing that, instead it displays the "maintenance mode" page with the connection error. I think it's fair enough that it should keep trying.

**Comment by dtretyakov** [comment]
@AndrewSav, thanks for reporting. I've created the following issue in TeamCity tracker: https://youtrack.jetbrains.com/issue/TW-53631

You could watch for it to be notified on resolution.
