### ISSUE TITLE
404 for http://teamcityserver/update/vsAddinInstallerv4.msi

### ISSUE THREAD

**Issue by Alex2357** [JetBrains/teamcity-docker-server#21]
Hi, 

The problem might come from an agent. I have created server using 

```text
sudo docker images --digests

REPOSITORY                  TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
jetbrains/teamcity-server   latest              sha256:c55ae3bfcc281948ab3d24bd79c7daef273d901b12589f2c0c7f1a0090c90f8e   ee31fe3f953e        2 days ago          1.52GB
```

```text
PS C:\Users\Administrator> docker images --digests

REPOSITORY                 TAG                        DIGEST                                                                    IMAGE ID            CREATED             SIZE
jetbrains/teamcity-agent   latest-windowsservercore   sha256:83a5674220ee6b231fa0213df164ed9f6d846df9f55ca14bf7d02127b9e1e201   695468c564a6        2 days ago          14.2GB
PS C:\Users\Administrator>
```

When I try to download addinInstaller I get 404.

**Comment by dtretyakov** [comment]
@Alex2357, could you please describe where did you found this link?

If you navigate to the `http://teamcityserver/profile.html` page you will see that to download VS Add-in web installer you need to use the following URL `http://teamcityserver/update/vsAddinWebInstaller.exe`.

Another way is to download ReSharper web installer from the following page: https://www.jetbrains.com/resharper/download/#section=web-installer

**Comment by Alex2357** [comment]
sorry, I can't find the place where was that link. If I find it again I will reopen

**Comment by mortengjesing** [comment]
The link is can be found on the Code Inpection tab, when trying to navigate to the error, and the addin is not installed.

**Comment by dtretyakov** [comment]
@mortengjesing, thanks for details, will fix it in the next bug fix release: https://youtrack.jetbrains.com/issue/TW-57260
