### ISSUE TITLE
Add support for Perforce

### ISSUE THREAD

**Issue by wbagdon** [JetBrains/teamcity-docker-server#24]
Since mercurial and git are included in the server image, perforce should be as well.

If this is not wanted, at the very least, the package `apt-transport-https` should be added so that packages can be added via https package managers (we use Artifactory for mirroring apt repos)

**Comment by kir** [comment]
Hello, I've created a corresponding issue, please vote/watch: https://youtrack.jetbrains.com/issue/TW-58966

**Comment by stamepicmorg** [comment]
my solution is:
1. fork image
2. add to dockerfile
```
##################################################################
#                   perforce client binary
##################################################################
ARG P4_VERSION=r20.2
ARG P4_DOWNLOAD_URL=http://www.perforce.com/downloads/perforce/${P4_VERSION}/bin.linux26x86_64/p4
RUN wget -nv --random-wait -c -P /usr/bin ${P4_DOWNLOAD_URL} && \
         chmod +x /usr/bin/p4
```
