### ISSUE TITLE
10.0.3 does not stop on ctrl+C, different logging

### ISSUE THREAD

**Issue by carlpett** [JetBrains/teamcity-docker-server#3]
There are two changes for the worse in the 10.0.3 tag vs 10.0.2:
1. The container does not stop on sending ctrl+C when running in foreground mode (`docker run jetbrains/teamcity-server`, ie no `-d`). I have to do `docker stop` in another terminal.
2. There is much less logging. I'm not exactly sure what preset is changed, but I do not get INFO logging any more on 10.0.3.

**Comment by VladRassokhin** [comment]
Already fixed some time ago (8482ff19eef2ed9329923a5e7bf5a6f889a4080a) in `10.0.5`, `2017.1` and `latest`

**Comment by VladRassokhin** [comment]
As for second point, AFAIK there was no changes in logging profiles. If problem reproduces report it to https://youtrack.jetbrains.com/issues/TW
