### ISSUE TITLE
Script error ignored

### ISSUE THREAD

**Issue by raybooysen** [JetBrains/teamcity-docker-server#34]
As part of the documentation, custom scripts can be run if added to the `/services/` directory.

However, if that script errors, the process of starting the server continues. Should the startup procedure stop if one of these scripts returns with an error code?

My use case is a custom docker file that runs a script to ensure my version of the MySQL connector is available at startup.  I had an issue today when a server started and it was unable to download the files due to an intermittent network issue.

**Comment by kir** [comment]
Hi @raybooysen , have you considered changing the Dockerfile in a way which puts MySQL connector of the correct version directly into the Docker image? I'd consider this a more reliable way to handle this situation.

I'm not sure changing the behaviour of scripts is a good thing as it may break existing docker images which don't expect containers to fail in situations like yours.

**Comment by raybooysen** [comment]
Hi @kir .  I did this the first round, except it seems if I extract files into the jdbc folder as part of the dockerfile, the files are overwritten at some point.  Is this something TC does at first start? I.e. clean out the install dir?

It seems a bit dangerous to have TC start if the scripts that the developer has written fail, especially as it's hard to spot.

**Comment by kir** [comment]
Hi @raybooysen ,

   Hmm. JDBC drivers go into `$TEAMCITY_DATA_DIR/lib/jdbc` directory. And this directory (TEAMCITY_DATA_DIR) should be mounted into the teamcity-server container explicitly, and they are a part of your teamcity data directory. I.e. the right thing to do is to download JDBC drivers, put them into teamcity-data-dir/lib/jdbc, and provide teamcity-data-dir as a volume to teamcity server image in `docker  run` command, as described in the docs for the image.

  How your process differers, what are you trying to achieve?

  Thanks,

**Comment by raybooysen** [comment]
What I've got currently is a kubernetes setup where on first start, teamcity asks for some storage. K8 then gives it a volume which is mounted at the datadir point. 

What I'm trying to do is ensure, and this is for first run only, is that a teamcity server can start, download the right drivers and then be ready for setup without any manual steps.

**Comment by kir** [comment]
I see. Unfortunately, I'm not familiar with k8, but I suppose it should be possible to populate a volume with some data, for instance by running a container which does exactly that. I.e. create a container which would put drivers to lib/jdbc in to the named volume, and then pass this volume to TeamCity. Would it work?

**Comment by raybooysen** [comment]
Absolutely, however that's a manual step which I've been trying to avoid.  I think we may be digressing on the actual issue, which is that scripts that fail don't stop the container coming up.  Happy to chat about the volume population though if you want. :)

**Comment by kir** [comment]
I see :) 
I've added a bug report based on your request: https://youtrack.jetbrains.com/issue/TW-60676, cannot promise a ETA, though.

Thanks!

**Comment by kir** [comment]
It is going to be fixed in TeamCity 2020.2.1 bugfix update.
