### ISSUE TITLE
Multiple "Docker Support" build features in build configuration

### ISSUE THREAD

**Issue by casperfrx** [JetBrains/teamcity-docker-server#35]
Hi there,

Not sure if this is the right place to post it but here goes:

I am able to define multiple connections in any project configuration, yet for a single build configuration I am only able to select a single connection as the  "Docker Support" build feature. This is very unpractical when pulling multiple (private) docker registries with different user accounts. The option disappears as soon as you choose one connection.

I would assume this option would be available for multiple connections.

**Comment by cosysoft-ru** [comment]
+1, really need this feature

**Comment by casperfrx** [comment]
Sadly not a single reply yet. Sure hope this inconvenience can be solved since it's would be pretty simple to tweak I think. They've added the logic of making it disappear I think.

**Comment by dmitry-treskunov** [comment]
Hi, please follow the following issue in our issue tracker https://youtrack.jetbrains.com/issue/TW-58876
