### ISSUE TITLE
TeamCity pull error

### ISSUE THREAD

**Issue by wjonkerhulst** [JetBrains/teamcity-docker-server#39]
When pulling de TeamCity image I get an error. The TeamCity images with version 2020.1.5 and before worked flawlesly.

> [root@ip-172-31-42-182 buildserver]# docker pull jetbrains/teamcity-server:latest
latest: Pulling from jetbrains/teamcity-server
da7391352a9b: Already exists 
14428a6d4bcd: Already exists 
2c2d948710f2: Already exists 
0cac0228acac: Pull complete 
9ccd9d88894f: Extracting [==================================================>]  194.2MB/194.2MB
fba88a32f6ec: Download complete 
7fa5425a5cc6: Download complete 
1f5d6537c5de: Download complete 
d6444b49c756: Download complete 
90f55be57be1: Download complete 
65643554e584: Download complete 
895de0b83c18: Download complete 
fd05159ed85e: Download complete 
1d98c826be2b: Download complete 
failed to register layer: Error processing tar file(exit status 1): Container ID 3175151 cannot be mapped to a host ID

The error is happening because user namespacing is enabled on the Docker server.
* https://docs.docker.com/engine/security/userns-remap/
* https://circleci.com/docs/2.0/high-uid-error/

The server is running
* Centos 7
* Docker 20.10.1, build 831ebea

**Comment by GTnikito** [comment]
Hello, wjonkerhulst 

I have made a small patch to teamcity server dockerfile. 
My path could be found [here.](https://github.com/JetBrains/teamcity-docker-images/pull/15)

**Comment by kir** [comment]
Hi,

  This issue should be fixed soon in the release containers, see https://youtrack.jetbrains.com/issue/TW-71381

  Best,
