### ISSUE TITLE
Context path?

### ISSUE THREAD

**Issue by lucaskatayama** [JetBrains/teamcity-docker-server#5]
Hi 

How do I change context path? 
It looks like Teamcity is installed in a ROOT aka / ... but I want to put under `http://domain.com/tc` behind a nginx proxy.

So nginx should have something like this:

```
location /tc/ {
       proxy_pass http://loclahost:8111/;
}
```

How do I do that with this docker image?

I changed the Server URL in Administration... but that didn't change the path of every CSS or JS.

**Comment by VladRassokhin** [comment]
Hi,
Sorry for late answer.

There's no way to simply change context, though next steps could help:

1. Chroot into container using `docker exec -it CONTAINER_ID /bin/bash`
2. Run inside container:
```bash
cd /opt/teamcity
./bin/teamcity-server.sh stop
./bin/teamcity-server.sh configure --context=tc
exit
```
3. Restart container using `docker stop CONTAINER_ID; docker start CONTAINER_ID`

**Comment by VladRassokhin** [comment]
I've updated scripts, so next version of image would accept 'TEAMCITY_CONTEXT' env variable with context value.
Pass it to `docker run` as, e.g. `-e TEAMCITY_CONTEXT=/tc`
