### ISSUE TITLE
Upgrade to 10.0.5 version

### ISSUE THREAD

**Issue by fred01** [JetBrains/teamcity-docker-server#7]
Hi!
10.0.5 version released about 20 days ago. Seems released version is minor update, i think rebuilding of this image shouldn't be a very hard task, so please, upgrade it

**Comment by VladRassokhin** [comment]
@fred01 Take a look on tags page: https://hub.docker.com/r/jetbrains/teamcity-server/tags/ 
We release docker images simultaneously with other distribution types and also re-released `jetbrains/teamcity-server:10.0.5` 12 days ago with several fixes

**Comment by fred01** [comment]
Yes, sorry, my bad. Something wrong with private registry.My image builded on top of teamcity-server wasn't updated in registry
