### ISSUE TITLE
docker-base Image Is Missing

### ISSUE THREAD

**Issue by mattpwest** [JetBrains/teamcity-docker-server#8]
I'm trying to build my own TeamCity image based on your Dockerfile, because I want to download a plugin zip file before the data volume is created. However it seems I can't pull the base image as instructed in the README:

```
root@build01:~# docker pull jetbrains/teamcity-base
Using default tag: latest
Error response from daemon: manifest for jetbrains/teamcity-base:latest not found
```

Looks like the **latest** tag is missing on Docker Hub.

**Comment by VladRassokhin** [comment]
Yes, it's known issue. Unfortunately due to Oracle restrictions we cannot publish neither 'teamcity-base' image nor Dockerfile.
You can use any other image with JRE 8 installed in available in PATH or as JRE_HOME environment variable.

**Comment by VladRassokhin** [comment]
There's related [issue in our tracker](https://youtrack.jetbrains.com/issue/TW-48534).
