### ISSUE TITLE
JSP pre-compilation failed

### ISSUE THREAD

**Issue by dmarchant** [JetBrains/teamcity-docker-server#9]
I have the teamcity docker server paired with a postgres docker db. I am getting a periodic JSP pre-compilation failed warning. Any ideas on how to solve it?
```
[2017-05-02 22:59:00,466]   INFO -   jetbrains.buildServer.SERVER - JSP pre-compilation failed: http://172.31.67.107:8111/admin/cleanup/editCleanupRules.jsp?jsp_precompile=true, error: java.net.NoRouteToHostException: No route to host (Host unreachable)
```

**Comment by VladRassokhin** [comment]
Please describe which version of TeamCity do you use, IP address of server and  value of `Server URL` parameter in `Administration -> Global Settings`

**Comment by dmarchant** [comment]
The version is `TeamCity Professional 2017.1.1 (build 46654)` and the Server URL is `http://172.31.67.107:8111` I installed it yesterday using the docker command at https://www.jetbrains.com/teamcity/download/#section=docker 
![image](https://cloud.githubusercontent.com/assets/1421030/25661736/fbf85f74-2fce-11e7-830a-81c6e25e3577.png)

**Comment by dmarchant** [comment]
Here are the docker commands I used to install postgres and teamcity
```
POSTGRES_PASSWORD='<REPLACE_WITH_PASS>'
SETUP_TEAMCITY_SQL="create role teamcity with login password 'teamcity';create database teamcity owner teamcity;"
docker run --name some-postgres -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -d postgres
docker run -it --link some-postgres:postgres --rm -e "SETUP_TEAMCITY_SQL=$SETUP_TEAMCITY_SQL" -e "PGPASSWORD=$POSTGRES_PASSWORD" postgres bash -c 'exec echo $SETUP_TEAMCITY_SQL |psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres'
docker run -it --link some-postgres:postgres --name teamcity-server-instance -v /data/teamcity_server/datadir:/data/teamcity_server/datadir -v /var/log/teamcity:/opt/teamcity/logs -p 8111:8111 jetbrains/teamcity-server
```
I then setup the connection to the Postgres container in the screenshot below
![image](https://cloud.githubusercontent.com/assets/1421030/25662092/7477f6de-2fd0-11e7-8f6c-a9bf65a703a7.png)

**Comment by andrewlozoya** [comment]
I had the same issue however, I am also using a reverse proxy. The trick is to go through the initial setup under your localhost:<exposed port> and then once the setup is configured you can switch over to your IP or proxied URL. This seems like a bug

**Comment by pavelsher** [comment]
It's a bug, please watch it in our tracker: https://youtrack.jetbrains.com/issue/TW-50572
